Add .env file check; remove extra stuff; improve readme doc

diff --git a/tests/integration/smt_server/Dockerfile b/tests/integration/smt_server/Dockerfile
--- a/tests/integration/smt_server/Dockerfile
+++ b/tests/integration/smt_server/Dockerfile
@@ -1,10 +1,18 @@
 FROM registry.scc.suse.de/connect_sp2
 
-ADD files/smt_current.rpm /root/smt_current.rpm
+RUN [[ \
+-z "$SCC_REGSERVER_URL" || \
+-z "SCC_USERNAME" || \
+-z "$SCC_PASSWORD" || \
+-z "$SMT_DB_USER"  || \
+-z "$SMT_DB_PASSWORD"  || \
+-z "$MYSQL_ROOT_PASSWORD" \
+]] && echo "ERROR: Please set variables in .env file" && exit 1
 
 RUN zypper ref && zypper --non-interactive install --no-recommend \
     timezone patch mariadb-client libopenssl-devel
 
+ADD files/smt_current.rpm /root/smt_current.rpm
 RUN zypper --non-interactive --no-gpg-checks in --no-recommend /root/smt_current.rpm
 
 ADD files/run.sh /root/run.sh
