made cron setup easier and more flexible

diff --git a/cron/smt-daily b/cron/smt-daily
--- a/cron/smt-daily
+++ b/cron/smt-daily
@@ -6,29 +6,15 @@
 # It syncs the local SMT with the Novell NCC, creates a daily report
 # and updates the mirrored installation and update sources.
 
-
-SMTCMD=/usr/sbin/smt
 JOBS="ncc-sync report mirror"
-LOGDIR="/var/log/"
+SMTLOGRUN=/usr/lib/SMT/bin/smt-logrun
 
-if [ -x ${SMTCMD} ]
+${SMTLOGRUN} ${JOBS}
+
+if [ $? != 0 ]
 then
-
-  for JOB in ${JOBS}
-  do
-    if [ -x ${SMTCMD}-${JOB} ]
-    then
-      ${SMTCMD}-${JOB} -L ${LOGDIR}/smt-${JOB}.log
-    else
-      echo "WARNING: Could not find the SMT binary ${SMTCMD}-${JOB}"
-      echo "         Please make sure SMT is properly installed."
-    fi
-  done
-
-else
-  echo "Could not find the SMT binaries. Your SMT installation seems to be broken."
-  # in cronjobs always do an exit 0 - even on errors - exit 1 only in case of real panic
-  exit 0
+  echo "Warning: Errors occurred within smt-daily run"
 fi
 
+# in cronjobs always do an exit 0 - even on errors - exit 1 only in case of real panic
 exit 0
